### ISSUE TITLE
add-a-website

### ISSUE THREAD

**Issue by singworld** [aircloud/sync-to-github#1]
gpt4不支持
https://chat.openai.com/chat?model=gpt-4

**Comment by aircloud** [comment]
这个应该是支持的，可以确认下是遇到什么问题了吗
(如果是刚刚安装插件，刷新一下页面)

**Comment by singworld** [comment]
![image](https://user-images.githubusercontent.com/37404619/226911983-edecd1bd-305a-4a05-ad28-caed91a3c24e.png)
![image](https://user-images.githubusercontent.com/37404619/226912280-27361a83-c635-496f-a1c9-156044f13aa2.png)
第二条保存成功了  工作机器和回家后的机器  问题一样

**Comment by aircloud** [comment]
目前看应该是安装插件后没刷新页面，这个需要注入代码，所以刷新一次就好了
如果好了之后再出现，我们可以再看看

**Comment by aircloud** [comment]
暂时先关了，有新的问题随时回复打开
