### ISSUE TITLE
Sync Error: This site has not been added

### ISSUE THREAD

**Issue by yaosong5** [aircloud/sync-to-github#3]
一直提示  Sync Error: This site has not been added  刷新过页面，重启过浏览器，重新装过插件，都还一直提示 
![image](https://user-images.githubusercontent.com/34050879/232120654-86905307-46bf-4998-938b-afe56b572bcc.png)

<img width="702" alt="image" src="https://user-images.githubusercontent.com/34050879/232120798-3d2f79d0-7683-482c-be1f-e6de4d355b6a.png">

**Comment by aircloud** [comment]
chatgpt 修改了 url 的格式，稍后我重新适配下

**Comment by aircloud** [comment]
可以试试这个版本：https://github.com/aircloud/sync-to-github/releases/tag/v0.2.0

**Comment by yaosong5** [comment]
已解决

**Comment by gogl92** [comment]
Does this error appear again? one week again it was working but now I'm getting this same error with version v0.2.0

**Comment by hengqujushi** [comment]
> 

same here

**Comment by hengqujushi** [comment]
> > 
> 
> same here

when I move to v0.3.0, I fix it
